import { useEffect, useRef, useState } from 'react'
import { ArrowLeft, ArrowRight, Check, ChevronDown, Eye, EyeOff, FileText, HeartPulse, Home, LogOut, Menu, Plus, Search, UserRound, X } from 'lucide-react'
import { AuthProvider, useAuth } from './context/AuthContext'
import './App.css'

const doctorNav = [{ path: '/', label: 'Dashboard', icon: Home }, { path: '/doctor/add-report', label: 'Add Report', icon: Plus }, { path: '/doctor/reports', label: 'View Reports', icon: FileText }]
const patientNav = [{ path: '/admin', label: 'Dashboard', icon: Home }, { path: '/admin/doctors', label: 'Doctors', icon: UserRound }, { path: '/admin/reports', label: 'Reports', icon: FileText }]
const doctors = [{ id: 'DOC-1024', name: 'Dr. Arjun Mehta', specialty: 'Internal Medicine' }, { id: 'DOC-2048', name: 'Dr. Kavya Rao', specialty: 'Radiology' }]
const patientReports = [
  { id: 'RPT-24091', type: 'Blood Report', date: '2026-09-22', doctorId: 'DOC-1024', summary: 'Routine blood panel reviewed by your care team.' },
  { id: 'RPT-24107', type: 'X-Ray', date: '2026-09-28', doctorId: 'DOC-2048', summary: 'Chest X-ray report available for viewing.' },
  { id: 'RPT-24122', type: 'MRI Scan', date: '2026-10-02', doctorId: 'DOC-2048', summary: 'MRI findings and radiologist notes.' },
]
const doctorReports = [
  { id: 'RPT-D1024-01', doctorId: 'WORKER001', patientName: 'Riya Sharma', age: '34', phone: '9876501001', type: 'Blood Report', date: '2026-10-01' },
  { id: 'RPT-D1024-02', doctorId: 'WORKER001', patientName: 'Riya Sharma', age: '34', phone: '9876501001', type: 'X-Ray', date: '2026-10-04' },
  { id: 'RPT-D1024-03', doctorId: 'WORKER001', patientName: 'Aman Verma', age: '49', phone: '9876501002', type: 'MRI Scan', date: '2026-10-05' },
]

function navigate(path) { window.history.pushState({}, '', path); window.dispatchEvent(new PopStateEvent('popstate')) }
function formatDate(value) { return value ? new Date(value).toLocaleString([], { dateStyle: 'medium', timeStyle: 'short' }) : 'Not recorded' }
function Logo({ compact = false }) { return <div className="brand"><span className="brand-mark"><HeartPulse size={compact ? 18 : 22} /></span><span><strong>MediVault</strong>{!compact && <small>Clinical records hub</small>}</span></div> }
function Button({ children, variant = 'primary', icon: Icon, ...props }) { return <button className={`button button-${variant}`} {...props}>{Icon && <Icon size={17} />}{children}</button> }
function Field({ label, name, value, onChange, type = 'text', placeholder, required = false }) { return <label className="field"><span>{label}{required && <b> *</b>}</span><input type={type} name={name} value={value ?? ''} onChange={onChange} placeholder={placeholder} required={required} /></label> }
function PageHeader({ eyebrow, title, subtitle }) { return <div className="page-header"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{subtitle}</p></div> }

function Login() {
  const { worker, login } = useAuth(); const [accountType, setAccountType] = useState('employee'); const [form, setForm] = useState({ identifier: '', password: '' }); const [error, setError] = useState(''); const [show, setShow] = useState(false); const [loading, setLoading] = useState(false); const isPatient = accountType === 'admin'
  useEffect(() => { if (worker) navigate(worker.accountType === 'admin' ? '/admin' : '/') }, [worker])
  function chooseAccount(type) { setAccountType(type); setForm({ identifier: '', password: '' }); setError(''); setShow(false) }
  function submit(event) { event.preventDefault(); setError(''); if (!form.identifier || !form.password) return setError('Enter your email and password.'); setLoading(true); window.setTimeout(() => { const result = login(form.identifier, form.password, accountType); if (!result.success) setError('Incorrect credentials.'); setLoading(false) }, 350) }
  return <div className="login-page"><button type="button" className="signup-button" onClick={() => navigate('/signup')}>Sign up</button><div className="login-aside"><div className="login-brand-large"><Logo /></div></div><main className="login-card"><Logo compact /><div className="login-copy"><h2>Welcome back</h2><p>Choose your workspace to continue.</p></div><div className="account-switcher" role="tablist" aria-label="Choose account type"><button type="button" className={!isPatient ? 'selected' : ''} onClick={() => chooseAccount('employee')} role="tab" aria-selected={!isPatient}><HeartPulse size={17} /><span><strong>Doctor</strong><small>Care team workspace</small></span></button><button type="button" className={isPatient ? 'selected' : ''} onClick={() => chooseAccount('admin')} role="tab" aria-selected={isPatient}><UserRound size={17} /><span><strong>Patient</strong><small>Personal records</small></span></button></div><form onSubmit={submit}><Field label="Email" name="identifier" type="email" value={form.identifier} onChange={(event) => setForm({ ...form, identifier: event.target.value })} placeholder="Enter your email" required /><label className="field"><span>Password *</span><div className="password-wrap"><input type={show ? 'text' : 'password'} value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} placeholder="Enter your password" required /><button type="button" className="input-action" onClick={() => setShow(!show)} aria-label={show ? 'Hide password' : 'Show password'}>{show ? <EyeOff size={17} /> : <Eye size={17} />}</button></div></label><label className="checkbox"><input type="checkbox" defaultChecked /> <span>Remember me on this device</span></label>{error && <div className="feedback error">{error}</div>}<Button type="submit" disabled={loading}>{loading ? 'Signing...' : 'Sign in'}</Button></form></main></div>
}

function Signup() {
  const [form, setForm] = useState({ email: '', accountType: 'doctor', password: '', confirmPassword: '' }); const [error, setError] = useState(''); const [complete, setComplete] = useState(false)
  function submit(event) { event.preventDefault(); setError(''); if (!form.email || !form.password || !form.confirmPassword) return setError('Complete all fields.'); if (form.password !== form.confirmPassword) return setError('Passwords do not match.'); setComplete(true) }
  return <div className="login-page signup-page"><div className="login-aside"><div className="login-brand-large"><Logo /></div></div><main className="login-card"><Logo compact />{complete ? <div className="signup-success"><span className="success-icon"><Check size={28} /></span><h2>Account request received</h2><p>Your MediVault {form.accountType} account details are ready for setup.</p><Button onClick={() => navigate('/login')}>Back to sign in</Button></div> : <><div className="login-copy"><h2>Create your account</h2><p>Set up secure access to MediVault.</p></div><form onSubmit={submit}><Field label="Email" name="email" type="email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} placeholder="Enter your email" required /><label className="field"><span>Account type *</span><select value={form.accountType} onChange={(event) => setForm({ ...form, accountType: event.target.value })}><option value="doctor">Doctor</option><option value="patient">Patient</option></select></label><Field label="Password" name="password" type="password" value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} placeholder="Enter your password" required /><Field label="Confirm password" name="confirmPassword" type="password" value={form.confirmPassword} onChange={(event) => setForm({ ...form, confirmPassword: event.target.value })} placeholder="Confirm your password" required />{error && <div className="feedback error">{error}</div>}<Button type="submit">Create account</Button><button type="button" className="signup-back" onClick={() => navigate('/login')}>Back to sign in</button></form></>}</main></div>
}

function ProfileMenu() { const { worker, logout } = useAuth(); const [open, setOpen] = useState(false); const ref = useRef(null); useEffect(() => { function close(event) { if (ref.current && !ref.current.contains(event.target)) setOpen(false) } document.addEventListener('mousedown', close); return () => document.removeEventListener('mousedown', close) }, []); return <div className="profile-wrap" ref={ref}><button className="profile-trigger" onClick={() => setOpen(!open)} aria-expanded={open}><span className="avatar">{worker.name.charAt(0)}</span><span className="profile-name"><strong>{worker.name}</strong><small>{worker.accountType === 'admin' ? 'Patient' : 'Doctor'}</small></span><ChevronDown size={16} /></button>{open && <div className="profile-menu"><div className="menu-person"><span className="avatar large">{worker.name.charAt(0)}</span><div><strong>{worker.name}</strong><small>{worker.email}</small></div></div><button onClick={() => navigate('/profile')}>Profile</button><button className="logout" onClick={() => { logout(); navigate('/login') }}><LogOut size={16} /> Logout</button></div>}</div> }
function Shell({ children, path }) { const { worker } = useAuth(); const nav = worker.accountType === 'admin' ? patientNav : doctorNav; const [mobileOpen, setMobileOpen] = useState(false); return <div className="app-shell"><aside className={`sidebar ${mobileOpen ? 'mobile-open' : ''}`}><div className="sidebar-top"><Logo compact /><button className="close-mobile" onClick={() => setMobileOpen(false)} aria-label="Close navigation"><X size={20} /></button></div><nav>{nav.map(({ path: itemPath, label, icon: Icon }) => <button key={itemPath} className={path === itemPath ? 'active' : ''} onClick={() => { navigate(itemPath); setMobileOpen(false) }}><Icon size={19} /><span>{label}</span></button>)}</nav></aside>{mobileOpen && <button className="scrim" onClick={() => setMobileOpen(false)} aria-label="Close navigation" />}<div className="main-shell"><header className="topbar"><button className="menu-toggle" onClick={() => setMobileOpen(true)} aria-label="Open navigation"><Menu size={22} /></button><div className="topbar-brand"><Logo /></div><ProfileMenu /></header><main className="content">{children}</main></div></div> }

function Dashboard() { const cards = [{ title: 'Add Report', description: 'Create a report and link it to a patient under your care.', icon: Plus, path: '/doctor/add-report' }, { title: 'View Reports', description: 'Search and review reports for patients under your care.', icon: FileText, path: '/doctor/reports' }]; return <><PageHeader eyebrow="DOCTOR DASHBOARD" title="Your MediVault workspace" subtitle="Manage patient reports from one secure place." /><section className="feature-grid doctor-dashboard-tabs">{cards.map(({ title, description, icon: Icon, path }) => <button className="feature-card" key={path} onClick={() => navigate(path)}><span className="feature-icon"><Icon size={22} /></span><span className="feature-body"><strong>{title}</strong><span>{description}</span></span><ArrowRight className="feature-arrow" size={19} /></button>)}</section></> }
function PatientDashboard() { const cards = [{ title: 'Doctors', description: 'Choose a doctor and view the reports linked to your care.', icon: UserRound, path: '/admin/doctors' }, { title: 'Reports', description: 'Search your reports by report type or report ID.', icon: FileText, path: '/admin/reports' }]; return <><PageHeader eyebrow="PATIENT DASHBOARD" title="Your MediVault" subtitle="Access the doctors and reports connected to your patient account." /><section className="feature-grid patient-dashboard-tabs">{cards.map(({ title, description, icon: Icon, path }) => <button className="feature-card" key={path} onClick={() => navigate(path)}><span className="feature-icon"><Icon size={22} /></span><span className="feature-body"><strong>{title}</strong><span>{description}</span></span><ArrowRight className="feature-arrow" size={19} /></button>)}</section></> }
function DoctorAddReport() { const [form, setForm] = useState({ patientName: '', age: '', phone: '', type: '', file: null, comments: '' }); const [message, setMessage] = useState(''); function submit(event) { event.preventDefault(); setMessage(''); if (!form.patientName || !form.age || !form.phone || !form.type || !form.file) return setMessage('Complete the patient fields, report type, and report file.'); doctorReports.push({ id: `RPT-WORKER001-${doctorReports.length + 1}`, doctorId: 'WORKER001', patientName: form.patientName, age: form.age, phone: form.phone, type: form.type, fileName: form.file.name, comments: form.comments, date: new Date().toISOString() }); setForm({ patientName: '', age: '', phone: '', type: '', file: null, comments: '' }); event.target.reset(); setMessage('Report added successfully.'); } return <><Button variant="ghost" onClick={() => navigate('/')} icon={ArrowLeft}>Back</Button><PageHeader eyebrow="DOCTOR WORKSPACE" title="Add report" subtitle="Upload a hard copy and link it to a patient under your care." /><section className="form-card doctor-report-form"><form className="form-grid" onSubmit={submit}><Field label="Patient name" name="patientName" value={form.patientName} onChange={(event) => setForm({ ...form, patientName: event.target.value })} placeholder="Enter patient name" required /><Field label="Age" name="age" type="number" value={form.age} onChange={(event) => setForm({ ...form, age: event.target.value })} placeholder="Enter patient age" required /><Field label="Phone number" name="phone" value={form.phone} onChange={(event) => setForm({ ...form, phone: event.target.value })} placeholder="Enter patient phone" required /><Field label="Report type" name="type" value={form.type} onChange={(event) => setForm({ ...form, type: event.target.value })} placeholder="e.g. Blood Report, X-Ray" required /><label className="field full-width"><span>Report file *</span><input name="file" type="file" accept=".pdf,.jpg,.jpeg,.png" onChange={(event) => setForm({ ...form, file: event.target.files?.[0] || null })} required /><small>Upload the report hard copy as a PDF or image.</small></label><label className="field full-width"><span>Comments <small>(optional)</small></span><textarea name="comments" value={form.comments} onChange={(event) => setForm({ ...form, comments: event.target.value })} placeholder="Add an optional comment" rows="3" /></label>{message && <div className="feedback success full-width">{message}</div>}<div className="form-actions full-width"><Button type="submit">Add report</Button></div></form></section></> }
function DoctorReports() { const [query, setQuery] = useState({ patientName: '', phone: '' }); const reports = doctorReports.filter((report) => report.doctorId === 'WORKER001' && (!query.patientName || report.patientName.toLowerCase().includes(query.patientName.trim().toLowerCase())) && (!query.phone || report.phone.includes(query.phone.trim()))); return <><Button variant="ghost" onClick={() => navigate('/')} icon={ArrowLeft}>Back</Button><PageHeader eyebrow="DOCTOR WORKSPACE" title="View reports" subtitle="Search all reports for a patient under your care." /><section className="form-card patient-filter-card"><div className="form-grid two"><Field label="Patient name" name="patientName" value={query.patientName} onChange={(event) => setQuery({ ...query, patientName: event.target.value })} placeholder="Search patient name" /><Field label="Phone number" name="phone" value={query.phone} onChange={(event) => setQuery({ ...query, phone: event.target.value })} placeholder="Search phone number" /></div></section><section className="patient-report-list"><div className="list-heading"><div><h2>Patient reports</h2><p>{reports.length} reports found</p></div></div>{reports.length ? reports.map((report) => <article className="patient-report-row" key={report.id}><div className="patient-report-icon"><FileText size={18} /></div><div><strong>{report.type}</strong><small>{report.id} · {formatDate(report.date)}</small></div><span>{report.patientName} · {report.phone}</span><button className="button button-secondary" type="button">View report</button></article>) : <div className="empty-state"><h2>No reports found</h2><p>Check the patient name and phone number.</p></div>}</section></> }
function PatientDoctors() { const [selectedDoctor, setSelectedDoctor] = useState(''); const reports = patientReports.filter((report) => !selectedDoctor || report.doctorId === selectedDoctor); return <><Button variant="ghost" onClick={() => navigate('/admin')} icon={ArrowLeft}>Back</Button><PageHeader eyebrow="PATIENT RECORDS" title="Doctors" subtitle="Select a doctor to view the reports connected to your care." /><section className="form-card patient-filter-card"><label className="field"><span>Select doctor</span><select value={selectedDoctor} onChange={(event) => setSelectedDoctor(event.target.value)}><option value="">All doctors</option>{doctors.map((doctor) => <option value={doctor.id} key={doctor.id}>{doctor.name} · {doctor.specialty}</option>)}</select></label></section><section className="patient-report-list"><div className="list-heading"><div><h2>Reports under this doctor</h2><p>{reports.length} related reports</p></div></div>{reports.map((report) => <article className="patient-report-row" key={report.id}><div className="patient-report-icon"><FileText size={18} /></div><div><strong>{report.type}</strong><small>{report.id} · {formatDate(report.date)}</small></div><span>{doctors.find((doctor) => doctor.id === report.doctorId)?.name}</span><button className="button button-secondary" type="button">View report</button></article>)}</section></> }
function PatientReports() { const [query, setQuery] = useState({ type: '', id: '' }); const report = patientReports.find((item) => (!query.type || item.type === query.type) && (!query.id || item.id.toLowerCase().includes(query.id.trim().toLowerCase()))); return <><Button variant="ghost" onClick={() => navigate('/admin')} icon={ArrowLeft}>Back</Button><PageHeader eyebrow="PATIENT RECORDS" title="Reports" subtitle="Search for a report using its report type or ID." /><section className="form-card patient-filter-card"><div className="form-grid two"><label className="field"><span>Report type</span><select value={query.type} onChange={(event) => setQuery({ ...query, type: event.target.value })}><option value="">All report types</option>{[...new Set(patientReports.map((item) => item.type))].map((type) => <option key={type}>{type}</option>)}</select></label><Field label="Report ID" name="reportId" value={query.id} onChange={(event) => setQuery({ ...query, id: event.target.value })} placeholder="e.g. RPT-24091" /></div></section>{report ? <article className="form-card report-result"><div className="verified-banner"><Check size={19} /><div><strong>{report.type}</strong><span>{report.id} · {formatDate(report.date)}</span></div></div><div className="detail-card"><div><span>Doctor</span><strong>{doctors.find((doctor) => doctor.id === report.doctorId)?.name}</strong></div><div><span>Report type</span><strong>{report.type}</strong></div><div><span>Patient</span><strong>ADMIN001 · MediVault patient</strong></div><div><span>Report ID</span><strong>{report.id}</strong></div></div><p>{report.summary}</p><Button type="button">View full report</Button></article> : <div className="empty-state"><span className="empty-icon"><Search size={28} /></span><h2>No matching report</h2><p>Try another report type or check the report ID.</p></div>}</> }
function Profile() { const { worker, logout } = useAuth(); const [changingPassword, setChangingPassword] = useState(false); const [password, setPassword] = useState({ current: '', next: '', confirm: '' }); const [message, setMessage] = useState(''); function savePassword(event) { event.preventDefault(); if (!password.current || !password.next || !password.confirm) return setMessage('Complete all password fields.'); if (password.next !== password.confirm) return setMessage('New passwords do not match.'); setMessage('Password change request saved.'); setPassword({ current: '', next: '', confirm: '' }); setChangingPassword(false) } const isPatient = worker.accountType === 'admin'; return <><div className="profile-page-heading"><Button variant="ghost" onClick={() => navigate(isPatient ? '/admin' : '/')} icon={ArrowLeft}>Back</Button><PageHeader eyebrow="ACCOUNT" title="Profile" subtitle={isPatient ? 'Manage your MediVault patient account.' : 'Your MediVault doctor account details.'} /></div><div className="profile-card"><span className="avatar profile-avatar">{worker.name.charAt(0)}</span><div className="profile-detail"><h2>{worker.name}</h2><p>{isPatient ? 'Patient' : 'Doctor'}</p><div className="detail-card"><div><span>Name</span><strong>{worker.name}</strong></div><div><span>Email</span><strong>{worker.email}</strong></div><div><span>Password</span><strong>********</strong></div></div>{message && <div className="feedback success">{message}</div>}{changingPassword ? <form className="password-change-form" onSubmit={savePassword}><Field label="Current password" name="current" type="password" value={password.current} onChange={(event) => setPassword({ ...password, current: event.target.value })} placeholder="Enter current password" required /><Field label="New password" name="next" type="password" value={password.next} onChange={(event) => setPassword({ ...password, next: event.target.value })} placeholder="Enter new password" required /><Field label="Confirm new password" name="confirm" type="password" value={password.confirm} onChange={(event) => setPassword({ ...password, confirm: event.target.value })} placeholder="Confirm new password" required /><div className="form-actions"><Button type="submit">Save password</Button><Button type="button" variant="secondary" onClick={() => setChangingPassword(false)}>Cancel</Button></div></form> : <Button variant="secondary" onClick={() => { setMessage(''); setChangingPassword(true) }}>Change password</Button>}<Button variant="ghost" onClick={() => { logout(); navigate('/login') }} icon={LogOut}>Log out</Button></div></div></> }

function Router() { const { worker } = useAuth(); const [path, setPath] = useState(window.location.pathname); useEffect(() => { const onPop = () => setPath(window.location.pathname); window.addEventListener('popstate', onPop); return () => window.removeEventListener('popstate', onPop) }, []); useEffect(() => { const protectedPath = path !== '/login' && path !== '/signup'; if (!worker && protectedPath) navigate('/login'); if (worker && (path === '/login' || path === '/signup')) navigate(worker.accountType === 'admin' ? '/admin' : '/') }, [path, worker]); if (!worker) return path === '/signup' ? <Signup /> : <Login />; const pages = worker.accountType === 'admin' ? { '/admin': <PatientDashboard />, '/admin/doctors': <PatientDoctors />, '/admin/reports': <PatientReports />, '/profile': <Profile /> } : { '/': <Dashboard />, '/doctor/add-report': <DoctorAddReport />, '/doctor/reports': <DoctorReports />, '/profile': <Profile /> }; return <Shell path={path}>{pages[path] || (worker.accountType === 'admin' ? <PatientDashboard /> : <Dashboard />)}</Shell> }
function App() { return <AuthProvider><Router /></AuthProvider> }
export default App
